### ISSUE TITLE
GPX route doesn't match photo locations

### ISSUE THREAD

**Issue by emj04** [jmlich/geotagging#31]
In 0.6.0 the GPX route doesn't line up at all with when the photos were taken. Rolling back to 0.5.9 resolves this.

I'm using the Flatpak on Fedora.

**Comment by jmlich** [comment]
It could be related to https://github.com/jmlich/geotagging/pull/30
Can you provide your gpx file please?

**Comment by jmlich** [comment]
Could be issue related to time zone handling?

**Comment by emj04** [comment]
Sorry for the delay. Here's the GPX.
[2021-07-25-12-35-00.zip](https://github.com/jmlich/geotagging/files/7707011/2021-07-25-12-35-00.zip)
