### ISSUE TITLE
No file opening via network share?

### ISSUE THREAD

**Issue by bommelmeier** [jmlich/geotagging#39]
Hi, using flatpak version of geotagging: when opening files the network shares are not shown...
Is it possible to open files on network shares?

**Comment by jmlich** [comment]
Network share is SMB, NFS or something else? It is mounted or accessed via GVFS? 

Does that affect all types of files? JPEG files are using exiv2 and GPX are using Qt files API. 

Does other flatpak application work with network shares?

**Comment by jmlich** [comment]
Now I see. Flatpak suggests:

> As a general rule, Filesystem access should be limited as much as possible

So I selected HOME folder which should be enough for most of cases. It seems network filesystem, or photos on encrypted volume could be unreachable. 

The long description is at
https://docs.flatpak.org/en/latest/sandbox-permissions.html

The permission could be adjusted at
https://github.com/flathub/com.github.jmlich.geotagging/blob/master/com.github.jmlich.geotagging.json#L13 
but I am not sure which of the options should be taken. I am more less fine with HOME.

**Comment by jmlich** [comment]
Most probably the right permissions is as follows. I will implement that soon:
```
         "--talk-name=org.gtk.vfs", "--talk-name=org.gtk.vfs.*",
        "--filesystem=xdg-run/gvfs", "--filesystem=xdg-run/gvfsd",
```

**Comment by jmlich** [comment]
You can try check if it helped:
```
flatpak install --user https://dl.flathub.org/build-repo/19488/com.github.jmlich.geotagging.flatpakref
```
