### ISSUE TITLE
App crashed on launch

### ISSUE THREAD

**Issue by eragrostis** [jmlich/geotagging#40]
Running Ubuntu the program crashes on launch

>lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy

>flatpak run com.github.jmlich.geotagging
QML debugging is enabled. Only use this in a safe environment.
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QColorSpace(), profile  QSurfaceFormat::NoProfile)
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QColorSpace(), profile  QSurfaceFormat::NoProfile)
Could not initialize GLX

**Comment by jmlich** [comment]
Please provide more information such as back trace. Flatpak version of geotagging runs on my Fedora 37 with Mate desktop. It sounds like combination of ubuntu/hardware/flatpak/qt/wayland issue.

**Comment by wsyxbcl** [comment]
on Archlinux, flatpak version works fine.

@eragrostis Check this, https://docs.flatpak.org/en/latest/debugging.html

**Comment by wsyxbcl** [comment]
Works fine on Arch linux.

> What command should I use to generate this? I tried the tutorial here but couldn't get it to work https://www.figuiere.net/hub/blog/?2019/10/11/878-getting-a-stack-trace-out-of-a-flatpak

@eragrostis Try `flatpak update` first to ensure you have the latest build. If there's still a issue, check https://docs.flatpak.org/en/latest/debugging.html

**Comment by eragrostis** [comment]
I guess updating worked (or maybe something else on my system changed in the past month). Either way, I can now run the program. 

Thank you
