### ISSUE TITLE
Flatpak installation fails

### ISSUE THREAD

**Issue by sm8ps** [jmlich/geotagging#41]
I have been using Geotagging for quite some time but now I cannot install it on Kubuntu 22.10.

Manually launching `flatpak install flathub com.github.jmlich.geotagging` gives
```
Error: while fetching app/com.github.jmlich.geotagging/x86_64/stable from remote flathub: opcode set-read-source: Opening content object b11c060c2121427ee9995e84568a2fbaa81edf5282669918020756e2b47361e1: Couldn't find file object 'b11c060c2121427ee9995e84568a2fbaa81edf5282669918020756e2b47361e1'
Error: Failed to install com.github.jmlich.geotagging: while fetching from app/com.github.jmlich.geotagging/x86_64/stable von der Gegenstelle flathub: opcode set-read-source: Opening content object b11c060c2121427ee9995e84568a2fbaa81edf5282669918020756e2b47361e1: Couldn't find file object 'b11c060c2121427ee9995e84568a2fbaa81edf5282669918020756e2b47361e1'
```
On https://copr.fedorainfracloud.org/coprs/jmlich/laa/package/com.github.jmlich.geotagging/ I see that builds have failed consistently since package version  0.6.1-2022072915.

**Comment by jmlich** [comment]
copr builds are failing because fedora was missing some qt6 package. I will check its status soon

**Comment by jmlich** [comment]
copr build now works for f37, f38, and rawhide. f36 is still broken due to dependency

**Comment by jmlich** [comment]
please provide more information, I am not able to reproduce the issue. This seems to be an flathub issue.
