### ISSUE TITLE
Wrong naming of term F-stop

### ISSUE THREAD

**Issue by ashed** [jmlich/geotagging#43]
Maybe it is mistyping when naming. 
Correct me if I wrong, please.

During a translation process of geotagging app i18n strings I found a term "F-number (F-spot)" at string 43.

https://app.transifex.com/jozef-mlich/geotagging/translate/#ru_RU/translation-com-github-jmlich-geotagging-en-us-ts--master/301160075

I asked about it you and you wrote: "the code points to Exif.Photo.FNumber see https://github.com/jmlich/geotagging/blob/master/exifreaderwriter.cpp#L396 Not sure if it is right number."

Ok. Lets try to search "FNumber" with context "Exif.Photo"
Found at
https://exiv2.org/tags.html
0x829d | 33437 | Photo | Exif.Photo.FNumber | Rational | The F number.

Search definition of "F-number"
Found at:
https://en.wikipedia.org/wiki/F-number
The f-number is also known as the focal ratio, f-ratio, or **f-stop**, and it is a key factor in determining the [depth of field](https://en.wikipedia.org/wiki/Depth_of_field), [diffraction](https://en.wikipedia.org/wiki/Diffraction), and [exposure](https://en.wikipedia.org/wiki/Exposure_(photography)) of a photograph.

Not "F-Spot" but "F-Stop" if you mean "f-number".

![fspot-mean-fstop-2023-07-10-15-35-39](https://github.com/jmlich/geotagging/assets/6615946/e99df10d-c79e-4f2f-b491-be0ab4fe269d)

**Comment by jmlich** [comment]
Its F SPOT not F STOP

**Comment by jmlich** [comment]
Thanks for explanation. It took some time, but I finally understand what was the issue
