### ISSUE TITLE
Flatpak end-of-life runtimes

### ISSUE THREAD

**Issue by Not-Sure-Whats-Going-On** [jmlich/geotagging#44]
Running Geotagging v0.7.1 Flatpak of May 2023 on Linux Mint 21.2.  Flatpak update on Dec 11, 2023 failed as follows.
```
flatpak update
  Looking for updates…
  Info: org.kde.Platform//6.3 is end-of-life, with reason:
     We strongly recommend moving to the latest stable version of the Plaform and SDK
  Applications using this runtime:
     com.github.jmlich.geotagging
  Info: org.freedesktop.Platform.GL.default//21.08 is end-of-life, with reason:
     org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
```

**Comment by jmlich** [comment]
Thanks for report. Should be fixed by https://github.com/flathub/com.github.jmlich.geotagging/pull/5

**Comment by Not-Sure-Whats-Going-On** [comment]
Thanks for fixing Jozef.  Great software BTW.  Stupid Sony camera has no built-in GPS so need to use Sony app on linked android phone but the app isn't reliable.  Your software makes the problem go away - thanks!
