### ISSUE TITLE
flatpak not working on Ubuntu 23.10

### ISSUE THREAD

**Issue by JeckPeppinger** [jmlich/geotagging#46]
flatpak v0.7.2 not starting on Ubuntu 23.10, some QT failure as shown below.
 
![image](https://github.com/jmlich/geotagging/assets/35139202/179188bb-19ec-4bb9-b683-29df50ab2bb9)

![image](https://github.com/jmlich/geotagging/assets/35139202/f360d605-0353-4d84-91b7-0d1c42a51ce5)

reinstalled flatpak installation several times, QT is properly installed as far as i can see.

Tried to compile the sources on ubuntu, but this failed. Is there a deb for ubuntu, or can it be built on ubuntu?

Thx!

**Comment by emj04** [comment]
Also happening on Fedora 39.

**Comment by jmlich** [comment]
It seems that symbol is missing in flatpak runtime. 
```
$ c++filt _Zls6QDebugRK11QDockWidget
operator<<(QDebug, QDockWidget const&)
```

I am not sure which qDebug()  to remove. I might try rebuild with flatpak to see if I can get line of code in error message.

**Comment by Erick555** [comment]
There is confirmed ABI break in Qt 6.6.2 https://archlinux.org/todo/qt-662-abi-break/

**Comment by jmlich** [comment]
Thanks for reporting
